---
- name: Find the borgmatic executable.
  command:
    cmd: "which borgmatic"
  register: borgmatic_exec_result
  changed_when: false

- name: Create the borgmatic configuration directory.
  file:
    path: /etc/borgmatic
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Create the borgmatic configuration file.
  template:
    src: templates/config.yaml.j2
    dest: /etc/borgmatic/config.yaml
    owner: root
    group: root
    mode: "0644"
  tags: molecule-idempotence-notest
