---
- name: Find the borgmatic executable.
  ansible.builtin.stat:
    path: "{{ lookup('first_found', findme, errors='ignore') }}"
  register: borgmatic_exec_result
  vars:
    findme:
      - /root/.local/bin/borgmatic
      - /usr/local/bin/borgmatic
      - /usr/bin/borgmatic

- name: Check if the borgmatic executable has been found.
  assert:
    that: borgmatic_exec_result.stat.exists
    quiet: true
    fail_msg: Could not find the borgmatic executable.

- name: Create the borgmatic configuration directory.
  file:
    path: /etc/borgmatic
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Create the borgmatic configuration file.
  template:
    src: templates/config.yaml.j2
    dest: /etc/borgmatic/config.yaml
    owner: root
    group: root
    mode: "0644"
  tags: molecule-idempotence-notest
