---
# TODO: Install with apt when the debian package get updated.
- name: "Install required system packages."
  apt:
    name:
      - openssh-client
      - python3-venv
      - python3-pip
      - borgbackup
      # - borgmatic
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default('0') }}"
    state: present
    install_recommends: true

- name: "Remove required system packages."
  apt:
    name:
      - borgmatic
    state: absent

- name: "Install required python packages."
  pip:
    name:
      - borgmatic
    state: present
