---
- name: "Install required system packages."
  apt:
    name:
      - borgbackup
      - borgmatic
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default('0') }}"
    state: present
    install_recommends: true
