---
# TODO: Install with apt when the debian package get updated.
- name: "Install required system packages."
  apt:
    name:
      - openssh-client
      - borgbackup
      - "{{ if ansible_python.version.major == 3 'python3-pip' else 'python-pip' }}"
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default('0') }}"
    state: present
    install_recommends: true

- name: "Remove out of date system packages."
  apt:
    name:
      - borgmatic
    state: absent

- name: "Install required python packages."
  pip:
    name:
      - borgmatic
    state: present
