---
- name: Generate the ssh directory for root.
  file:
    path: "{{ borg_sshkey | dirname }}"
    state: directory
    recurse: yes
    mode: "700"
  tags: molecule-idempotence-notest

- name: Generate SSH key.
  community.crypto.openssh_keypair:
    path: "{{ borg_sshkey }}"
    type: ed25519
    comment: "borg@{{ inventory_hostname }}"
  register: ssh_key_result
