---
- name: Install the systemd service.
  ansible.builtin.template:
    src: templates/borgmatic.service.j2
    dest: /etc/systemd/system/borgmatic.service
    owner: root
    group: root
    mode: "0644"
    validate: "systemd-analyze verify %s"

- name: Install the systemd timer.
  ansible.builtin.template:
    src: templates/borgmatic.timer.j2
    dest: /etc/systemd/system/borgmatic.timer
    owner: root
    group: root
    mode: "0644"
    validate: "systemd-analyze verify %s"

- name: Enable the borgmatic timer.
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: yes
    name: borgmatic.timer
  tags: molecule-notest
