---
- name: Converge

  hosts: all

  vars:
    borg_source_directories: "/etc"
    borg_encryption_passphrase: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=64') }}"

  tasks:
    - name: "Include role"
      include_role:
        name: "{{ lookup('env', 'PWD') | regex_replace('^(/.+/)', '') }}"
