---
- name: Converge

  hosts: all

  vars:
    borg_source_directories: "/etc"

  tasks:
    - name: "Include role"
      include_role:
        name: "{{ lookup('env', 'PWD') | regex_replace('^(/.+/)', '') }}"
